# Generated by Django 3.2.9 on 2022-05-24 15:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20220523_2150'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name="users can't follow them selves",
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('followed_user')), _negated=True), name="users can't follow themselves"),
        ),
    ]
